version: "3.4"
services:
  service-gestionstockfournisseur_mongo_db_1:
    image: mongo:latest
    container_name: "service-gestionstockfournisseur_mongo_db_1"
    ports:
      - 27017:27017

  springboot-mongodb-stockfournisseur:
    image: springboot-mongodb:1.0
    container_name: "springboot-mongodb-stockfournisseur"
    ports:
      - 8080:8080
    links:
      - service-gestionstockfournisseur_mongo_db_1


